version: '3'
services:
  mysql-standalone:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=123987123
      - MYSQL_DATABASE=migrostest
    ports:
      - "3307:3306"

  springboot-docker-container:
    container_name: springboot
    image: springboot-docker-container
    environment:
      SPRING_DATASOURCE_URL: jbdc:mysql://mysql-standalone:3306
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone
    ports:
      - "8080:8080"