server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
  security:
    user:
      name: root
      password: root
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/migrostest${DB_PARAMS:?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

logging:
  level:
    org:
      springframework:
        security: DEBUG

springfox:
  documentation:
    enabled: ${SWAGGER_ENABLED:true}

### Test Profile
---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/migrostest${DB_PARAMS:?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}


### Dev Profile
---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/migrosdev${DB_PARAMS:?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

### Prod Profile
---

spring:
  config:
    activate:
      on-profile: master
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/migrosmaster${DB_PARAMS:?useSSL=false}
    username: ${DB_USERNAME:xxx}
    password: ${DB_PASSWORD:xxx}